networks:
  korp-network:
    external: true
    name: http-server-projeto-korp_korp-network

services:
  prometheus:
    image: prom/prometheus:v3.13.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - korp-network