{
 "title": "Projeto Korp - Observabilidade da API",
 "tags": [
  "korp",
  "golang",
  "nginx"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade da API (Health)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "Latência da API (Tempo de Resposta)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "Tempo de Resposta" }
   ]
  },
  {
   "title": "Volume Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total" }
   ]
  },
  {
   "title": "Taxa de Requisições por Segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Conexões em Tempo Real",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Ativas" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Aguardando" }
   ]
  }
 ]
}